RRR<-function(BIANLIANG=CLOSE,N=9)
{
  BIANLIANG<-as.numeric(BIANLIANG)
  SHIJI<-0
  REFBIANLIANG<-0
  REFBIANLIANG[1]<-BIANLIANG[1]
  for(i in 2:length(BIANLIANG))
  REFBIANLIANG[i]<-BIANLIANG[i-1]
  PANDUANBIANLIANG<-BIANLIANG-REFBIANLIANG
  for(i in 1:length(PANDUANBIANLIANG))
    ifelse(PANDUANBIANLIANG[i]>=0,SHIJI[i]<-PANDUANBIANLIANG[i],SHIJI[i]<-0)
  
  RSIZHI<-SMA(SHIJI,N,1)/SMA(abs(PANDUANBIANLIANG),N,1)*100
  return(RSIZHI)
}
