SHIJIXINHAO<-0
SHIJIXINHAO[1]<-CHUSHIXINHAO[1]
for(i in 2:length(ZHISUN))
{
  if(ZHISUN[i] == 1) XINHAOZHI<-CHUSHIXINHAO[i]
  if(ZHISUN[i] == 0 & CHUSHIXINHAO[i] == XINHAOZHI) SHIJIXINHAO[i]<-0
  if(ZHISUN[i] == 0 & CHUSHIXINHAO[i] == 0-XINHAOZHI) SHIJIXINHAO[i]<-CHUSHIXINHAO[i]
  else SHIJIXINHAO[i]<-0

}